package constants

var MONGO_SERVICE_NAME = "MONGO_SERVICE_NAME"
var MONGO_SERVICE_PORT = "MONGO_SERVICE_PORT"

var REDIS_SERVICE_NAME = "REDIS_SERVICE_NAME"
var REDIS_SERVICE_PORT = "REDIS_SERVICE_PORT"
