---
apiVersion: v1
kind: Service
metadata:
    name: backend-svc
    namespace: default
spec:
    type: ClusterIP
    selector:
        component: api
    ports:
         -   port: 80
             targetPort: 8000