---
apiVersion: v1
kind: Service
metadata:
    name: frontend-svc
    namespace: default
spec:
    type: ClusterIP
    selector:
        component: frontend
    ports:
         -   port: 80
             targetPort: 3000