---
apiVersion: v1
kind: Service
metadata:
    name: mongo-svc
    namespace: default
spec:
    type: ClusterIP
    selector:
        app: mongo
    ports:
         -   port: 80
             targetPort: 27017