---
apiVersion: v1
kind: Service
metadata:
    name: redis-svc
    namespace: default
spec:
    type: ClusterIP
    selector:
        component: redis
    ports:
         -   port: 80
             targetPort: 6379